/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import logicaNegocio.LogicaAplicacion;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author esauj
 */
public class ComponenteGuardar extends javax.swing.JDialog {

    /**
     * Creates new form ComponenteGuardar
     */
    private PantallaPrincipal pa;
    private LogicaAplicacion la;
    private String rutaArchivo;
    
    
    //constructor
    public ComponenteGuardar(java.awt.Frame parent, boolean modal, LogicaAplicacion la) {
        super(parent, modal);
        pa = (PantallaPrincipal) parent;
        this.la = la;
        initComponents();
        rutaArchivo = mostrarPantallaGuardar();
        la.setRutaInformes(rutaArchivo);
        jTextRutaArchivo.setText(rutaArchivo);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuardar = new javax.swing.JButton();
        jTextRutaArchivo = new javax.swing.JTextField();
        jPanelDiscoDuro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGuardar.setText(org.openide.util.NbBundle.getMessage(ComponenteGuardar.class, "ComponenteGuardar.jButtonGuardar.text")); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextRutaArchivo.setText(org.openide.util.NbBundle.getMessage(ComponenteGuardar.class, "ComponenteGuardar.jTextRutaArchivo.text")); // NOI18N

        javax.swing.GroupLayout jPanelDiscoDuroLayout = new javax.swing.GroupLayout(jPanelDiscoDuro);
        jPanelDiscoDuro.setLayout(jPanelDiscoDuroLayout);
        jPanelDiscoDuroLayout.setHorizontalGroup(
            jPanelDiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDiscoDuroLayout.setVerticalGroup(
            jPanelDiscoDuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButtonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextRutaArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jPanelDiscoDuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jTextRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanelDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
         try {
            //La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(la.getListaCarreras());
            //Creamos el map para los parametros, en este caso va vacío.
            //Map parametros = new HashMap();
            Map parametros = new HashMap<>();
            JasperPrint print
                    = JasperFillManager.fillReport("informes/informe_CarrerasSinAcabar.jasper", parametros,
                            dataSource);
            JasperExportManager.exportReportToPdfFile(print,rutaArchivo);
        } catch (JRException ex) {
            Exceptions.printStackTrace(ex);
        }
         
         dispose();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JPanel jPanelDiscoDuro;
    private javax.swing.JTextField jTextRutaArchivo;
    // End of variables declaration//GEN-END:variables

    public String mostrarPantallaGuardar(){
        String ruta  = "";
        File fichero  = null;
        JFileChooser jc = new JFileChooser();
        int seleccion=jc.showSaveDialog(jPanelDiscoDuro);
        
        //si el usuario pincha en guardar
        if(seleccion == JFileChooser.APPROVE_OPTION){
            
            fichero = jc.getSelectedFile();
            ruta = fichero.getAbsolutePath();
        }
        return ruta+".pdf";
    }
}