/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.HashMap;
import java.util.Map;
import logicaNegocio.LogicaAplicacion;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author esauj
 */
public class PantallaInformes extends javax.swing.JDialog {

    private LogicaAplicacion la;
    PantallaPrincipal pa;
    
    public PantallaInformes(java.awt.Frame parent, boolean modal, LogicaAplicacion logicaAplicacion) {
        super(parent, modal);
        pa = (PantallaPrincipal) parent;
        this.la = logicaAplicacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonInformeCarrerasSin = new javax.swing.JButton();
        jButtonInformeCarrera = new javax.swing.JButton();
        jButtonInformeCarreraAcabada = new javax.swing.JButton();
        jButtonInformeCorredor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonInformeCarrerasSin.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonInformeCarrerasSin.text")); // NOI18N
        jButtonInformeCarrerasSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeCarrerasSinActionPerformed(evt);
            }
        });

        jButtonInformeCarrera.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonInformeCarrera.text")); // NOI18N
        jButtonInformeCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeCarreraActionPerformed(evt);
            }
        });

        jButtonInformeCarreraAcabada.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonInformeCarreraAcabada.text")); // NOI18N
        jButtonInformeCarreraAcabada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeCarreraAcabadaActionPerformed(evt);
            }
        });

        jButtonInformeCorredor.setText(org.openide.util.NbBundle.getMessage(PantallaInformes.class, "PantallaInformes.jButtonInformeCorredor.text")); // NOI18N
        jButtonInformeCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeCorredorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInformeCarrerasSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInformeCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInformeCarreraAcabada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInformeCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInformeCarrerasSin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInformeCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInformeCarreraAcabada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInformeCorredor)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInformeCarrerasSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeCarrerasSinActionPerformed

        ComponenteGuardar cg = new ComponenteGuardar(pa,true,la);
        cg.setVisible(true);
        dispose();
    /**    
        try {
            //La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(la.getListaCarreras());
            //Creamos el map para los parametros, en este caso va vacío.
            //Map parametros = new HashMap();
            Map parametros = new HashMap<>();
            JasperPrint print
                    = JasperFillManager.fillReport("informes/informe_carreras_1.jasper", parametros,
                            dataSource);
            JasperExportManager.exportReportToPdfFile(print, "informes/informe_carreras_1.pdf");
        } catch (JRException ex) {
            Exceptions.printStackTrace(ex);
        }
        * */
    }//GEN-LAST:event_jButtonInformeCarrerasSinActionPerformed

    private void jButtonInformeCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeCarreraActionPerformed
        
        int modeloCombo = 1;
       //muestro la pantalla con el combo con todas las carreras
       PantallaTodasCarreras pantallaTodasCarreras = new PantallaTodasCarreras(pa,true,la,modeloCombo);
       pantallaTodasCarreras.setVisible(true);
       //borro la pantalla
       dispose();
    }//GEN-LAST:event_jButtonInformeCarreraActionPerformed

    private void jButtonInformeCarreraAcabadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeCarreraAcabadaActionPerformed
        
        int modeloCombo = 2;
       //muestro la pantalla con el combo con las carreras acabadas
       PantallaTodasCarreras pantallaTodasCarreras = new PantallaTodasCarreras(pa,true,la,modeloCombo);
       pantallaTodasCarreras.setVisible(true);
       //borro la pantalla
       dispose();
    }//GEN-LAST:event_jButtonInformeCarreraAcabadaActionPerformed

    private void jButtonInformeCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeCorredorActionPerformed
        
         int modeloCombo = 3;
       //muestro la pantalla con el combo con las carreras acabadas
       PantallaTodasCarreras pantallaTodasCarreras = new PantallaTodasCarreras(pa,true,la,modeloCombo);
       pantallaTodasCarreras.setVisible(true);
       //borro la pantalla
       dispose();
    }//GEN-LAST:event_jButtonInformeCorredorActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInformeCarrera;
    private javax.swing.JButton jButtonInformeCarreraAcabada;
    private javax.swing.JButton jButtonInformeCarrerasSin;
    private javax.swing.JButton jButtonInformeCorredor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
