/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logicaNegocio.LogicaAplicacion;

/**
 *
 * @author esauj
 */
public class PantallaCorredor extends javax.swing.JDialog {

    private LogicaAplicacion logicaAplicacion ;
    private PantallaPrincipal ppal;
    
    
    public PantallaCorredor(java.awt.Frame parent, boolean modal,LogicaAplicacion logicaAplicacion) {
        super(parent, modal);
        initComponents();
        logicaAplicacion = new LogicaAplicacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultasCorredor = new javax.swing.JPanel();
        jButtonAniadir = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAniadir.setText("AÑADIR");
        jButtonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirActionPerformed(evt);
            }
        });

        jButtonModificar.setText("MODIFICAR");

        jButtonBorrar.setText("BORRAR");

        jButtonConsultar.setText("CONSULTAR");

        javax.swing.GroupLayout jPanelConsultasCorredorLayout = new javax.swing.GroupLayout(jPanelConsultasCorredor);
        jPanelConsultasCorredor.setLayout(jPanelConsultasCorredorLayout);
        jPanelConsultasCorredorLayout.setHorizontalGroup(
            jPanelConsultasCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelConsultasCorredorLayout.createSequentialGroup()
                .addComponent(jButtonModificar)
                .addGap(26, 26, 26)
                .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
            .addGroup(jPanelConsultasCorredorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsultasCorredorLayout.setVerticalGroup(
            jPanelConsultasCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultasCorredorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAniadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultasCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanelConsultasCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanelConsultasCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirActionPerformed
        PantallaDatosCorredor pantalla = new PantallaDatosCorredor(ppal,true,logicaAplicacion);
        pantalla.setVisible(true);
        
    }//GEN-LAST:event_jButtonAniadirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JPanel jPanelConsultasCorredor;
    // End of variables declaration//GEN-END:variables
}
